name: oncemore
favicon: null
layout_spectrum: 0.3142129483167082
typography_spectrum: 0.43622237676754594
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.10170117719098926
  lightness: 0.7679337114095688
  saturation: 0.7892446820624173
  rhythmicContrast: 0.034422944532707334
purpose: []
